CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

BACKBONE: 'resnet'
MODEL: 'voxelpose'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'output/dance'
LOG_DIR: 'output/dance'
WORKERS: 8
PRINT_FREQ: 200

DATASET:
  COLOR_RGB: True
  ROOT: "data/DanceF_easymocap"
  TRAIN_DATASET: 'demo'
  TRAIN_HEATMAP_SRC: 'image'
  TEST_DATASET: 'demo'
  TEST_HEATMAP_SRC: 'image'
  ROOTIDX: 2
  CAMERA_NUM: 4
  ORI_IMAGE_WIDTH: 1296
  ORI_IMAGE_HEIGHT: 972

NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_coco_rh_1.4.pth"
  IMAGE_SIZE:
  - 512
  - 384
  HEATMAP_SIZE:
  - 128
  - 96
  NUM_JOINTS: 15
  SIGMA: 3

TRAIN:
  BATCH_SIZE: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001

TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 1

CAPTURE_SPEC:
  # SPACE_SIZE:
  #   - 8000.0
  #   - 8000.0
  #   - 2000.0
  # SPACE_CENTER:
  #   - 0.0
  #   # - -500.0
  #   - 0.0
  #   - 800.0
  SPACE_SIZE:
    - 4000.0
    - 4000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0 # 120.0
    # - -500.0 # -600.0
    - 0.0 # -600.0
    - 1000.0
  VOXELS_PER_AXIS:
    - 80
    - 80
    - 20
  MAX_PEOPLE: 10
  MIN_SCORE: 0.3
  
INDIVIDUAL_SPEC:
  SPACE_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  VOXELS_PER_AXIS:
    - 64
    - 64
    - 64